server:
  #ip: 127.0.0.1 # 설정없이 디폴트 ip 설정.
  port: 9091
  servlet:
    context-path: /

logging:
  file:
    path: logs/teatime
  config: config/logback.xml
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      location: d:\\spring\\temp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://172.16.48.45/ims
    #username: root
    #password: Castis365*
    url: jdbc:mariadb://172.16.48.45/ims
    username: root
    password: Castis365*
    #hikari
    hikari:
      idle-timeout: 300
      max-lifetime: 300
  jpa:
    show-sql: true
    format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
      jdbc.batch_size: 100
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false

jwt:
  secret:
    signature: "aafsdzxcvasdfzxbbbasdfzxcvasdfzxcv"

scheduler:
  vacation:
    fixedRate: 30000

useJwt: true

uploadLocation:
  path: d:\\spring\\upload\\

holiday:
  openApi:
    serviceKey: jwV6WKPafup8qqgOZ%2BtRbkR3lsuAsYJ4bbUyg8QfP9yh3CbEBOkb7n%2BB91U11TK0v2KjGdZ3CIkx0hwhg2vnTQ%3D%3D

cbank:
  companyId: teatime
  openApi:
    otp:
      url: http://bank.castis.net/cbank/api/v1/otp
    transfer:
      url: http://bank.castis.net/cbank/api/v1/transfer
    viewAccount:
      url: http://bank.castis.net/cbank/api/v1/account/info/
    history:
      url: http://bank.castis.net/cbank/api/v1/account/history

kakao:
  api-key: NCSWVSZSVEPHMDYP
  secret: PVI4TYAMCT3GPPQDKRARO7O7Z3MBT9L3
  pfid: KA01PF220906035048833ynNa3G1G1YN
  messaging:
    template:
      assistance-apply-alarm: KA01TP240119012537734foTq4BqWv70
    url: https://api.coolsms.co.kr
    tel-origin: 01071649777
